### ISSUE TITLE
Forma de obtener el reverso de la carta?

### ISSUE THREAD

**Issue by josefalanga** [JessVel/sakura-card-capture-api#1]
Estaria bueno tener otro endpoint para obtener los reversos de las cartas Clow y Sakura, o en su defecto incluirlo en el objeto de cada carta.

**Comment by JessVel** [comment]
Hola @josefalanga !
Si, tengo pensado incluir eso en la api en algún momento. Si te animas, podrías contribuir e incluirlo!

Saludos!
