### ISSUE TITLE
Pagination and additional card info

### ISSUE THREAD

**Issue by Lmendev** [JessVel/sakura-card-capture-api#2]
😃 Hello Jess! 

Are you improving the sakura api? I have some ideas for pagination and additional card info. 

I want to contribute and help coding

**Comment by JessVel** [comment]
Hello @Lmendev !
Yes, I have many ideas to improve the api but I'm afraid I don't have much time.
Please, feel free to contribute! :)

**Comment by Lmendev** [comment]
I will be sincere with you.. I ran "npm install" and then "npm run dev". After that, get a mongodb error. Possibly because I don't have process.env.DB_MONGO on my src/config/db.js local env 🤣 do you know what should I do?

**Comment by Lmendev** [comment]
Pagination implemented #3
